/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class drone_plugins_frei0r_actors_Frei0r */

#ifndef _Included_drone_plugins_frei0r_actors_Frei0r
#define _Included_drone_plugins_frei0r_actors_Frei0r
#ifdef __cplusplus
extern "C" {
#endif
#undef drone_plugins_frei0r_actors_Frei0r_COMPLETE
#define drone_plugins_frei0r_actors_Frei0r_COMPLETE -1L
#undef drone_plugins_frei0r_actors_Frei0r_CLASSNAME
#define drone_plugins_frei0r_actors_Frei0r_CLASSNAME 1L
#undef drone_plugins_frei0r_actors_Frei0r_FULLNAME
#define drone_plugins_frei0r_actors_Frei0r_FULLNAME 2L
#undef drone_plugins_frei0r_actors_Frei0r_LINKS
#define drone_plugins_frei0r_actors_Frei0r_LINKS 4L
#undef drone_plugins_frei0r_actors_Frei0r_CONTENTS
#define drone_plugins_frei0r_actors_Frei0r_CONTENTS 8L
#undef drone_plugins_frei0r_actors_Frei0r_DEEP
#define drone_plugins_frei0r_actors_Frei0r_DEEP 16L
#undef drone_plugins_frei0r_actors_Frei0r_ATTRIBUTES
#define drone_plugins_frei0r_actors_Frei0r_ATTRIBUTES 32L
/*
 * Class:     drone_plugins_frei0r_actors_Frei0r
 * Method:    openLibrary
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_drone_plugins_frei0r_actors_Frei0r_openLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     drone_plugins_frei0r_actors_Frei0r
 * Method:    closeLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_drone_plugins_frei0r_actors_Frei0r_closeLibrary
  (JNIEnv *, jobject);

/*
 * Class:     drone_plugins_frei0r_actors_Frei0r
 * Method:    f0r_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_drone_plugins_frei0r_actors_Frei0r_f0r_1init
  (JNIEnv *, jobject);

/*
 * Class:     drone_plugins_frei0r_actors_Frei0r
 * Method:    f0r_deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_drone_plugins_frei0r_actors_Frei0r_f0r_1deinit
  (JNIEnv *, jobject);

/*
 * Class:     drone_plugins_frei0r_actors_Frei0r
 * Method:    f0r_construct
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_drone_plugins_frei0r_actors_Frei0r_f0r_1construct
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     drone_plugins_frei0r_actors_Frei0r
 * Method:    f0r_destruct
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_drone_plugins_frei0r_actors_Frei0r_f0r_1destruct
  (JNIEnv *, jobject, jint);

/*
 * Class:     drone_plugins_frei0r_actors_Frei0r
 * Method:    f0r_update
 * Signature: (ID[I[I)V
 */
JNIEXPORT void JNICALL Java_drone_plugins_frei0r_actors_Frei0r_f0r_1update
  (JNIEnv *, jobject, jint, jdouble, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
