/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class drone_artkp_kernel_TrackerMultiMarker */

#ifndef _Included_drone_artkp_kernel_TrackerMultiMarker
#define _Included_drone_artkp_kernel_TrackerMultiMarker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     drone_artkp_kernel_TrackerMultiMarker
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_drone_artkp_kernel_TrackerMultiMarker_init
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat);

/*
 * Class:     drone_artkp_kernel_TrackerMultiMarker
 * Method:    calc
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_drone_artkp_kernel_TrackerMultiMarker_calc
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     drone_artkp_kernel_TrackerMultiMarker
 * Method:    getNumDetectedMarkers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_drone_artkp_kernel_TrackerMultiMarker_getNumDetectedMarkers
  (JNIEnv *, jobject);

/*
 * Class:     drone_artkp_kernel_TrackerMultiMarker
 * Method:    setUseDetectLite
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_drone_artkp_kernel_TrackerMultiMarker_setUseDetectLite
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     drone_artkp_kernel_TrackerMultiMarker
 * Method:    getDetectedMarkers
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_drone_artkp_kernel_TrackerMultiMarker_getDetectedMarkers
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     drone_artkp_kernel_TrackerMultiMarker
 * Method:    getDetectedMarker
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_drone_artkp_kernel_TrackerMultiMarker_getDetectedMarker
  (JNIEnv *, jobject, jint);

/*
 * Class:     drone_artkp_kernel_TrackerMultiMarker
 * Method:    calcOpenGLMatrixFromDetectedMarker
 * Signature: (IFFF[F)F
 */
JNIEXPORT jfloat JNICALL Java_drone_artkp_kernel_TrackerMultiMarker_calcOpenGLMatrixFromDetectedMarker
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
