/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class drone_frei0r_jni_Frei0r */

#ifndef _Included_drone_frei0r_jni_Frei0r
#define _Included_drone_frei0r_jni_Frei0r
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    _openLibrary
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_drone_frei0r_jni_Frei0r__1openLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    _closeLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_drone_frei0r_jni_Frei0r__1closeLibrary
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_drone_frei0r_jni_Frei0r_init
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_drone_frei0r_jni_Frei0r_deinit
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    construct
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_drone_frei0r_jni_Frei0r_construct
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    destruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_drone_frei0r_jni_Frei0r_destruct
  (JNIEnv *, jobject, jlong);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    update
 * Signature: (JD[I[I)V
 */
JNIEXPORT void JNICALL Java_drone_frei0r_jni_Frei0r_update
  (JNIEnv *, jobject, jlong, jdouble, jintArray, jintArray);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    update2
 * Signature: (JD[I[I[I[I)V
 */
JNIEXPORT void JNICALL Java_drone_frei0r_jni_Frei0r_update2
  (JNIEnv *, jobject, jlong, jdouble, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getParamInfo
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_drone_frei0r_jni_Frei0r_getParamInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    setParamValue
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_drone_frei0r_jni_Frei0r_setParamValue
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getParamValue
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_drone_frei0r_jni_Frei0r_getParamValue
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_drone_frei0r_jni_Frei0r_getName
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getAuthor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_drone_frei0r_jni_Frei0r_getAuthor
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getPluginType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_drone_frei0r_jni_Frei0r_getPluginType
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getColorModel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_drone_frei0r_jni_Frei0r_getColorModel
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getFrei0rVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_drone_frei0r_jni_Frei0r_getFrei0rVersion
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getMajorVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_drone_frei0r_jni_Frei0r_getMajorVersion
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getMinorVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_drone_frei0r_jni_Frei0r_getMinorVersion
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    nParams
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_drone_frei0r_jni_Frei0r_nParams
  (JNIEnv *, jobject);

/*
 * Class:     drone_frei0r_jni_Frei0r
 * Method:    getExplanation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_drone_frei0r_jni_Frei0r_getExplanation
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
