######################################################################
# Automatically generated by qmake (1.07a) Fri Feb 16 01:28:11 2007
######################################################################

CONFIG += release

TEMPLATE = lib
INCLUDEPATH += /System/Library/Frameworks/JavaVM.framework/Headers ../contrib/Frei0r/spec
TARGET = Frei0rJNI
QMAKE_POST_LINK = mv libFrei0rJNI* lib/

# Input
HEADERS += drone_frei0r_jni_Frei0r.h
SOURCES += drone_frei0r_jni_Frei0r.cpp
