# Package-specific
TARGET := drone_frei0r_jni_Frei0r
SOURCES := drone_frei0r_jni_Frei0r.cpp

INCLUDES += -I../contrib/Frei0r/spec

# Common
OPTIONSDIR := ../../common/
include $(OPTIONSDIR)Makefile.common