#!/bin/bash 

#building external libs
cd lib/ffmpeg
./configure --extra-cflags=-fno-common --disable-ffserver --disable-ffplay
make
cd ../../

cd lib/liblo
./configure --enable-shared
make
cd ../../

cd lib/agg23
./configure
make
cd ../../
