#!/bin/bash 

#building external libs
cd lib/ffmpeg
./configure --enable-libx264 --enable-gpl --extra-cflags=-fno-common --disable-ffserver --disable-ffplay
make
cd ../../

#cd lib/liblo
#./configure --enable-shared
#make
#cd ../../

cd lib/agg23
make
cd ../../
