######################################################################
# Automatically generated by qmake (1.07a) Sat May 22 15:57:15 2004
######################################################################

include (../../../../config.pro)

CONFIG += qtestlib

unix:!macx:QMAKE_CXXFLAGS += -rdynamic

DEPENDPATH += src
INCLUDEPATH += ../../ ../../types ../../../contrib/frei0r/spec/
LIBS += -L../../../../lib -ldroneCore
DESTDIR = ../../../../


#mac
macx:LIBS += /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
macx:LIBS += /System/Library/Frameworks/Carbon.framework/Carbon

#linux
unix:!macx:QMAKE_RPATH = -Wl,-rpath,lib/,-rpath,


HEADERS += TestGearMaker.h TestSchema.h TestGearInfo.h
SOURCES += testcore.cpp

