# Package-specific
TARGET := drone_artkp_kernel_TrackerMultiMarker
SOURCES := drone_artkp_kernel_TrackerMultiMarker.cpp

INCLUDES += -I$(ARTKP)/include/
LIBRARIES += -L$(ARTKP)/lib/ -lARToolKitPlus

# Common
OPTIONSDIR := ../../../common/
include $(OPTIONSDIR)Makefile.common