/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class drone_frei0r_jni_Frei0r_Instance */

#ifndef _Included_drone_frei0r_jni_Frei0r_Instance
#define _Included_drone_frei0r_jni_Frei0r_Instance
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
