Document: drone
Title: Debian drone Manual
Author: <insert document author here>
Abstract: This manual describes what drone is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/drone/drone.sgml.gz

Format: postscript
Files: /usr/share/doc/drone/drone.ps.gz

Format: text
Files: /usr/share/doc/drone/drone.text.gz

Format: HTML
Index: /usr/share/doc/drone/html/index.html
Files: /usr/share/doc/drone/html/*.html

  
