######################################################################
# Automatically generated by qmake (1.07a) Sat May 22 15:57:15 2004
######################################################################

CONFIG = qt warn_on thread
include (../../../config.pro)

TEMPLATE = subdirs
SUBDIRS = core gears
