/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class drone_artkp_kernel_TrackerMultiMarkerImpl */

#ifndef _Included_drone_artkp_kernel_TrackerMultiMarkerImpl
#define _Included_drone_artkp_kernel_TrackerMultiMarkerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     drone_artkp_kernel_TrackerMultiMarkerImpl
 * Method:    _createTrackerHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_drone_artkp_kernel_TrackerMultiMarkerImpl__1createTrackerHandle__
  (JNIEnv *, jclass);

/*
 * Class:     drone_artkp_kernel_TrackerMultiMarkerImpl
 * Method:    _createTrackerHandle
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_drone_artkp_kernel_TrackerMultiMarkerImpl__1createTrackerHandle__II
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
