OS=$(shell uname -s)
include $(OPTIONSDIR)/Makefile_options_$(OS)

JNILIB := lib$(TARGET).$(EXT)

all:
	@echo ">> Trying to compile" $(TARGET) "for" $(OS) " <<"
	$(CXX) $(CXXFLAGS) $(INCLUDES) -o $(JNILIB) $(SOURCES)
	@mv $(JNILIB) lib/
	@echo ">> done <<"

clean:
	@echo ">> Cleaning up <<"
	\rm -f core *.o lib/$(JNILIB)
	@echo ">> done <<"

Makefile_options_$(OS):
	@echo "**** PLEASE CHECK YOUR MAKEFILE_OPTIONS for >>" $(OS) "<< ****"
