/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker */

#ifndef _Included_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker
#define _Included_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker_init
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat);

/*
 * Class:     ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker
 * Method:    calc
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker_calc
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker
 * Method:    getNumDetectedMarkers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker_getNumDetectedMarkers
  (JNIEnv *, jobject);

/*
 * Class:     ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker
 * Method:    setUseDetectLite
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker_setUseDetectLite
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker
 * Method:    getDetectedMarkers
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker_getDetectedMarkers
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker
 * Method:    getDetectedMarker
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker_getDetectedMarker
  (JNIEnv *, jobject, jint);

/*
 * Class:     ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker
 * Method:    calcOpenGLMatrixFromDetectedMarker
 * Signature: (IFFF[F)V
 */
JNIEXPORT jfloat JNICALL Java_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarker_calcOpenGLMatrixFromDetectedMarker
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
