/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ptolemy_actor_lib_artkp_kernel_TrackerMultiMarkerImpl */

#ifndef _Included_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarkerImpl
#define _Included_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarkerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ptolemy_actor_lib_artkp_kernel_TrackerMultiMarkerImpl
 * Method:    _createTrackerHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ptolemy_actor_lib_artkp_kernel_TrackerMultiMarkerImpl__1createTrackerHandle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
